# Generated by Django 4.2.6 on 2025-09-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
